# Generated by Django 4.0.3 on 2022-04-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
                ('platform_used', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows')], max_length=10)),
            ],
        ),
    ]
