# Generated by Django 4.0.3 on 2022-04-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0002_artifact_slug_alter_artifact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='slug',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
