# Generated by Django 4.0.3 on 2022-04-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifact', '0005_alter_artifact_platform_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='platform_used',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows')], max_length=10),
        ),
    ]
